### PR TITLE
Fix exporter_lag off-by-one bug

### LINKED ISSUE #32: kafka_consumer_group_exporter_lag == 1 when fully caught up
When the exporter is fully caught up, the lag reports as 1 instead of 0.

Topic highwaters are the offset where the next message will be written. Since the exporter is subtracting the most recently read message, this will result in a difference of 1.

We don't see this for the normal lag metric because consumer groups commit the offset they should begin reading from, similar to topics.

### PR DESCRIPTION
**Pull request by jutley**
Fixes #32

### CODE REVIEW

**Comment by jutley** [comment]
I think this suggestion is very sensible. Happy to make the patch once I get the chance.

**Comment by jutley** [comment]
@braedon This has been implemented. Please review.

**Comment by braedon** [comment]
Looks good to me - thanks!

**Comment by braedon** [comment]
Released in [0.5.3](https://github.com/braedon/prometheus-kafka-consumer-group-exporter/releases/tag/0.5.3)

**Pull request merged**
